obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_inf.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_sysfs.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_pinctrl.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sp7021_gpio_inf.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sp7021_gpio_ops.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sp7021_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl.o
