#
## Makefile for the display subsystem
#

ccflags-y += -Werror
ccflags-y += -Wformat-security

obj-$(CONFIG_VIDEO_I143_DISP) += display_i143.o
display_i143-objs := display.o disp_dve.o disp_dmix.o disp_tgen.o disp_osd.o disp_vpp.o
