#
# Makefile for the CBDMA module driver
#

	# call from kernel build system
	obj-$(CONFIG_SUNPLUS_CBDMA) += sp_cbdma.o
	obj-$(CONFIG_SUNPLUS_CBDMA_PROXY) += sp_cbdma_proxy.o

clean:
	rm -tf *.o *~ *.ko
