#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= cpu.o

ifndef CONFIG_SKIP_LOWLEVEL_INIT
obj-y	+= lowlevel_init.o
endif

obj-$(CONFIG_SP_TIMER)	+= sp_timer.o
# IP test
# obj-y	+= rtc_tst.o
# obj-y	+= dram_tst.o
