#
# Makefile for the AXI Monitor module drivers.
#

	# call from kernel build system

	obj-$(CONFIG_SUNPLUS_AXI_MONITOR) += sp_axi.o

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions