obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl.o pinctrl_inf_sp7021.o sppctl_sysfs.o sppctl_pinctrl.o gpio_inf_sp7021.o sppctl_gpio_ops.o sppctl_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL_I143) += sppctl.o pinctrl_inf_i143.o sppctl_sysfs.o sppctl_pinctrl.o gpio_inf_i143.o sppctl_gpio_ops.o sppctl_gpio.o
