obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl.o sppctl_inf.o sppctl_sysfs.o sppctl_pinctrl.o sp7021_gpio_inf.o sp7021_gpio_ops.o sp7021_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL_I143) += sppctl.o sppctl_inf_i143.o sppctl_sysfs.o sppctl_pinctrl_i143.o i143_gpio_inf.o sp7021_gpio_ops.o sp7021_gpio.o
