# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 Sunplus - All Rights Reserved
# Hammer Hsieh, Sunplus Software Engineering, hammer.hsieh@sunplus.com

obj-$(CONFIG_VIDEO_SP7021) += sp7021_display.o disp_dve.o disp_dmix.o disp_tgen.o disp_vpp.o disp_osd.o disp_hdmitx.o